/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '8/2/17 8:49 AM' with Gradle 2.14.1
 *
 * @author IT000531, @date 8/2/17 8:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
